#ifndef LIBQMSSTYLES_GLOBAL_H
#define LIBQMSSTYLES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBQMSSTYLES_LIBRARY)
#define LIBQMSSTYLES_EXPORT Q_DECL_EXPORT
#else
#define LIBQMSSTYLES_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBQMSSTYLES_GLOBAL_H
